### ISSUE TITLE
Data augmentation code release

### ISSUE THREAD

**Issue by RRRed22** [Syniez/SlaBins#3]
Hi. Thanks for the great work and the contribution to this research field. If any chance that the author could release some of the code for data augmentation before the full code release? Thanks so so so so much.

**Comment by Syniez** [comment]
First of all, thank you for your interest. I think our main network code is unavailable because it is confidential. However, I think I can share our data-processing codes and pre-processed (angle-augmented) datasets soon.

The following datasets will be released:
- **SynWoodScape**: RGB, Depth, LUTs
- **KITTI-360**: RGB, Depth, LUTs, calibration JSON file

Thank you.

**Comment by Syniez** [comment]
I uploaded the datasets and provided the download link at #2.
Please check it.

Thank you.
